## provide the name of the namespace
namespace:
  name: staging

## define service 
service:
  port: 5111

## set the number of replicas for an application 
replicaCount: 3

## define & limit computational resources 
resources:
  limits:
    memory: "128Mi"
    cpu: "500m"
  requests: 
    memory: "90Mi"
    cpu: "300m"