## provide the name of the namespace
namespace:
  name: sandbox

## define service 
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

## define the image to execute with the Deployment 
image:
  repository: neuroit/techtrends
  tag: latest
  pullPolicy: IfNotPresent

## set the number of replicas for an application 
replicaCount: 1

## define & limit computational resources 
resources:
  limits:
    memory: "128Mi"
    cpu: "500m"
  requests: 
    memory: "64Mi"
    cpu: "250m"

## define container port 
containerPort: 3111

## define probe path 
livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz